#!/usr/bin/env bash
# Generate SHA-256 checksums for ONNX model files.
# Run after downloading models to create/update the checksum manifest.
# Run from the workspace root (memory_arena/).
#
# Usage:
#   bash scripts/generate_checksums.sh              # Base models only (MiniLM, GLiNER)
#   bash scripts/generate_checksums.sh --multimodal  # Multimodal models only (Whisper, CLIP)
#   bash scripts/generate_checksums.sh --all         # All models

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
MODELS_DIR="$(cd "$(dirname "$0")/.." && pwd)/models"
MODE="${1:-base}"

# Determine which models and checksum file to use
case "$MODE" in
    --multimodal)
        CHECKSUM_FILE="$SCRIPTS_DIR/multimodal_checksums.sha256"
        HEADER_TEXT="# Ucotron Multimodal Model Checksums (SHA-256)"
        MODEL_DIRS="whisper-tiny clip-vit-base-patch32"
        ;;
    --all)
        # Generate both files
        echo "Generating base model checksums..."
        bash "$SCRIPTS_DIR/generate_checksums.sh"
        echo ""
        echo "Generating multimodal model checksums..."
        bash "$SCRIPTS_DIR/generate_checksums.sh" --multimodal
        exit 0
        ;;
    *)
        CHECKSUM_FILE="$SCRIPTS_DIR/model_checksums.sha256"
        HEADER_TEXT="# Ucotron ONNX Model Checksums (SHA-256)"
        MODEL_DIRS="all-MiniLM-L6-v2 gliner_small-v2.1"
        ;;
esac

echo "=== Generating Model Checksums ==="
echo "Models directory: $MODELS_DIR"
echo "Output file:      $CHECKSUM_FILE"
echo "Model dirs:       $MODEL_DIRS"
echo ""

# Clear existing checksum file
cat > "$CHECKSUM_FILE" << HEADER
$HEADER_TEXT
# Format: <sha256>  <relative-path-from-models/>
# Generated by scripts/generate_checksums.sh
# Used by scripts/verify_models.sh and CI cache validation
HEADER

# Find model files in specified directories and compute checksums
cd "$MODELS_DIR"
FOUND=0
for dir in $MODEL_DIRS; do
    if [ ! -d "$dir" ]; then
        echo "[WARN] Directory not found: $dir (download models first)"
        continue
    fi
    find "$dir" -type f \( -name "*.onnx" -o -name "*.json" -o -name "*.txt" \) | sort | while read -r file; do
        if command -v sha256sum &>/dev/null; then
            hash=$(sha256sum "$file" | awk '{print $1}')
        else
            hash=$(shasum -a 256 "$file" | awk '{print $1}')
        fi
        echo "$hash  $file" >> "$CHECKSUM_FILE"
        echo "[OK] $file"
    done
    FOUND=1
done

echo ""
echo "=== Checksums written to $CHECKSUM_FILE ==="
echo "Commit this file to enable CI model cache verification."
